chore: CRW-3531 update to golang-1.18 /...
che-incubator/kubernetes-image-puller pull request #115
Opened 2022-11-21 19:19 UTC by nickboldt

### What does this PR do?

chore: CRW-3531 update to golang-1.18 / delete obsolete centos.Dockerfile (just use Dockerfile)

Change-Id: Iad09c1101172219466288c1b8ac7fb664aa9c7ee
Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

2022-11-22 14:16 UTC, ibuziuk reviewed
why the do you want to remove centos image?

2022-11-22 14:25 UTC, ibuziuk requested changes
-1 for centos image removal

2022-11-22 14:47 UTC, nickboldt commented
Well, the centos and ubi8 minimal images are of comparable size:

53M:
![image](https://user-images.githubusercontent.com/227597/203343101-b8037515-03fc-4738-ae1f-1ff2ae461e1a.png)

51-56M (depending on arch):
![image](https://user-images.githubusercontent.com/227597/203343223-58737add-38c9-4ad1-b20e-453cdc1c6bc4.png)

But if you want to keep it and just update to go 1.18, that's cool.

Note that when I build them locally, the centos7 based build is 434M, while the ubi8-minimal one is only 134 M.

2022-11-22 14:47 UTC, ibuziuk approved these changes

2022-11-22 14:53 UTC, merged

2022-11-27 08:41 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [imagepuller_3.x/39](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/39/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/39/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/39/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/39/git)

2022-11-27 08:54 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [sync-to-downstream_3.x/1445](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1445/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1445/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1445/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1445/git)

2022-11-27 08:59 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [get-sources-rhpkg-container-build_3.x/1435](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1435/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1435/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1435/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1435/git)

2022-11-27 09:25 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [push-latest-container-to-quay_3.x/1140](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1140/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1140/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1140/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1140/git)

2022-11-27 09:35 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [push-latest-container-to-quay_3.x/1140](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1140/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1140/)<br /><blockquote>Copied: imagepuller-rhel8; <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/>/job/DS_CI/job/update-digests_3.x</a> triggered;<br /><a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/>/job/DS_CI/job/Releng/job/copyIIBsToQuay</a> triggered for OCP v4.12 v4.11 v4.10</blockquote>

2022-11-27 09:35 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [copyIIBsToQuay/210](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/210/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/210/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/210/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/210/git)

2022-11-27 09:35 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [get-sources-rhpkg-container-build_3.x/1435](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1435/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1435/)<br /><blockquote>imagepuller : 3.x :: <a href='https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=49224528'> Build  49224528</a> : <a href=https://quay.io/devspaces/imagepuller-rhel8:3.4-7>quay.io/devspaces/imagepuller-rhel8:3.4-7</a> <br /> SUCCESS; copied to quay; <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1140/>/DS_CI/push-latest-container-to-quay_3.x/1140</a> triggered</blockquote>

2022-11-27 09:42 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [sync-to-downstream_3.x/1445](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1445/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1445/)<br /><blockquote>Build container: devspaces-imagepuller synced;  <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1435/>/DS_CI/get-sources-rhpkg-container-build_3.x/1435</a> triggered; </blockquote>

2022-11-27 09:42 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [imagepuller_3.x/39](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/39/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/39/)<br /><blockquote>Upstream sync done; <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1445/>/DS_CI/sync-to-downstream_3.x/1445</a> triggered</blockquote>

2022-11-27 10:37 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [copyIIBsToQuay/210](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/210/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/210/)<br /><blockquote>arches = x86_64, s390x, ppc64le; <br />&nbsp;&nbsp;* LATEST DS  OPERATOR BUNDLE = <a href=https://quay.io/repository/devspaces/devspaces-operator-bundle?tab=tags>registry-proxy.engineering.redhat.com/rh-osbs/devspaces-operator-bundle:3.4-64</a><br />&nbsp;&nbsp;* LATEST DWO OPERATOR BUNDLE = <a href=https://quay.io/repository/devworkspace/devworkspace-operator-bundle?tab=tags>registry-proxy.engineering.redhat.com/rh-osbs/devworkspace-operator-bundle:0.17-1</a><br />+ x86_64-rhel8 IIB(s) copied: <br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.12-379910-360667-x86_64>quay.io/devspaces/iib:3.4-v4.12-379910-360667-x86_64</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.12-x86_64>quay.io/devspaces/iib:3.4-v4.12-x86_64</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:next-v4.12-x86_64>quay.io/devspaces/iib:next-v4.12-x86_64</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.11-379909-360662-x86_64>quay.io/devspaces/iib:3.4-v4.11-379909-360662-x86_64</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.11-x86_64>quay.io/devspaces/iib:3.4-v4.11-x86_64</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:next-v4.11-x86_64>quay.io/devspaces/iib:next-v4.11-x86_64</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.10-379908-360655-x86_64>quay.io/devspaces/iib:3.4-v4.10-379908-360655-x86_64</a><br />+ ppc64le-rhel8 IIB(s) copied: <br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.12-379910-360667-ppc64le>quay.io/devspaces/iib:3.4-v4.12-379910-360667-ppc64le</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.12-ppc64le>quay.io/devspaces/iib:3.4-v4.12-ppc64le</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:next-v4.12-ppc64le>quay.io/devspaces/iib:next-v4.12-ppc64le</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.11-379909-360662-ppc64le>quay.io/devspaces/iib:3.4-v4.11-379909-360662-ppc64le</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.11-ppc64le>quay.io/devspaces/iib:3.4-v4.11-ppc64le</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:next-v4.11-ppc64le>quay.io/devspaces/iib:next-v4.11-ppc64le</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.10-379908-360655-ppc64le>quay.io/devspaces/iib:3.4-v4.10-379908-360655-ppc64le</a><br />&nbsp;&nbsp;* LATEST DS  OPERATOR BUNDLE = <a href=https://quay.io/repository/devspaces/devspaces-operator-bundle?tab=tags>registry-proxy.engineering.redhat.com/rh-osbs/devspaces-operator-bundle:3.4-65</a><br />+ s390x-rhel8 IIB(s) copied: <br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.12-379910-360667-s390x>quay.io/devspaces/iib:3.4-v4.12-379910-360667-s390x</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.11-380310-360662-s390x>quay.io/devspaces/iib:3.4-v4.11-380310-360662-s390x</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.11-s390x>quay.io/devspaces/iib:3.4-v4.11-s390x</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:next-v4.11-s390x>quay.io/devspaces/iib:next-v4.11-s390x</a><br />&nbsp;&nbsp;+ <a href=https://quay.io/devspaces/iib:3.4-v4.10-380309-360655-s390x>quay.io/devspaces/iib:3.4-v4.10-380309-360655-s390x</a></blockquote>

2022-11-27 11:04 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [update-digests_3.x/1341](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1341/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1341/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1341/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1341/git)

2022-11-27 11:05 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [update-digests_3.x/1341](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1341/): [![UNSTABLE](https://img.shields.io/badge/Build-UNSTABLE-yellow?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1341/)<br /><blockquote>No new images detected: nothing to do!</blockquote>

2022-12-04 08:41 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [imagepuller_3.x/40](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/40/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/40/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/40/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/40/git)

2022-12-04 08:50 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [sync-to-downstream_3.x/1522](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1522/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1522/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1522/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1522/git)

2022-12-04 08:53 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [get-sources-rhpkg-container-build_3.x/1510](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1510/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1510/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1510/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1510/git)

2022-12-04 09:07 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [push-latest-container-to-quay_3.x/1205](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1205/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1205/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1205/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1205/git)

2022-12-04 10:20 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [push-latest-container-to-quay_3.x/1205](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1205/): [![UNSTABLE](https://img.shields.io/badge/Build-UNSTABLE-yellow?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1205/)<br /><blockquote>Copied: imagepuller-rhel8; Quay/Brew version mismatch; all Quay images updated; <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/>/job/DS_CI/job/update-digests_3.x</a> triggered;<br /><a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/>/job/DS_CI/job/Releng/job/copyIIBsToQuay</a> triggered for OCP v4.12 v4.11 v4.10</blockquote>

2022-12-04 10:20 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [get-sources-rhpkg-container-build_3.x/1510](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1510/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1510/)<br /><blockquote>imagepuller : 3.x :: <a href='https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=49384554'> Build  49384554</a> : <a href=https://quay.io/devspaces/imagepuller-rhel8:3.4-8>quay.io/devspaces/imagepuller-rhel8:3.4-8</a> <br /> SUCCESS; copied to quay; <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1205/>/DS_CI/push-latest-container-to-quay_3.x/1205</a> triggered</blockquote>

2022-12-04 10:20 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [copyIIBsToQuay/277](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/277/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/277/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/277/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/277/git)

2022-12-04 10:51 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [sync-to-downstream_3.x/1522](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1522/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1522/)<br /><blockquote>Build container: devspaces-imagepuller synced;  <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1510/>/DS_CI/get-sources-rhpkg-container-build_3.x/1510</a> triggered; </blockquote>

2022-12-04 10:51 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [imagepuller_3.x/40](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/40/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/imagepuller_3.x/40/)<br /><blockquote>Upstream sync done; <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1522/>/DS_CI/sync-to-downstream_3.x/1522</a> triggered</blockquote>

2022-12-04 11:56 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [update-digests_3.x/1422](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1422/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1422/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1422/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1422/git)

2022-12-04 12:00 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [operator-bundle_3.x/596](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/operator-bundle_3.x/596/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/operator-bundle_3.x/596/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/operator-bundle_3.x/596/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/operator-bundle_3.x/596/git)

2022-12-04 12:07 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [sync-to-downstream_3.x/1528](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1528/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1528/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1528/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1528/git)

2022-12-04 12:10 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [get-sources-rhpkg-container-build_3.x/1519](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1519/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1519/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1519/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1519/git)

2022-12-04 12:17 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [push-latest-container-to-quay_3.x/1216](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1216/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1216/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1216/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1216/git)

2022-12-04 12:21 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [copyIIBsToQuay/287](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/287/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/287/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/287/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/287/git)

2022-12-04 12:22 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [push-latest-container-to-quay_3.x/1216](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1216/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1216/)<br /><blockquote>Copied: devspaces-operator-bundle; bundle-generated updated;<br /><a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/Releng/job/copyIIBsToQuay/>/job/DS_CI/job/Releng/job/copyIIBsToQuay</a> triggered for OCP v4.12 v4.11 v4.10</blockquote>

2022-12-04 12:22 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [get-sources-rhpkg-container-build_3.x/1519](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1519/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1519/)<br /><blockquote>devspaces-operator-bundle : 3.x :: <a href='https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=49384902'> Build  49384902</a> : <a href=https://quay.io/devspaces/devspaces-operator-bundle:3.4-93>quay.io/devspaces/devspaces-operator-bundle:3.4-93</a> <br /> SUCCESS; copied to quay; <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/push-latest-container-to-quay_3.x/1216/>/DS_CI/push-latest-container-to-quay_3.x/1216</a> triggered</blockquote>

2022-12-04 12:28 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [sync-to-downstream_3.x/1528](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1528/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1528/)<br /><blockquote>Build container: devspaces-operator-bundle synced;  <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.x/1519/>/DS_CI/get-sources-rhpkg-container-build_3.x/1519</a> triggered;  <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dsc_3.x/>/job/DS_CI/job/dsc_3.x</a> triggered; </blockquote>

2022-12-04 12:28 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [operator-bundle_3.x/596](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/operator-bundle_3.x/596/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/operator-bundle_3.x/596/)<br /><blockquote>Upstream sync done; <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/sync-to-downstream_3.x/1528/>/DS_CI/sync-to-downstream_3.x/1528</a> triggered</blockquote>

2022-12-04 12:30 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [dsc_3.x/449](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dsc_3.x/449/): [Console](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dsc_3.x/449/console), [Changes](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dsc_3.x/449/changes), [Git Data](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dsc_3.x/449/git)

2022-12-04 12:33 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [update-digests_3.x/1422](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1422/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/update-digests_3.x/1422/)<br /><blockquote>Detected new images: rebuild operator-bundle<br />* udi; <a href=https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/operator-bundle_3.x/596/>/DS_CI/operator-bundle_3.x/596</a> triggered</blockquote>

2022-12-04 12:36 UTC, devstudio-release commented
Build [3.4](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/) :: [dsc_3.x/449](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dsc_3.x/449/): [![SUCCESS](https://img.shields.io/badge/Build-SUCCESS-brightgreen?style=plastic&logo=redhat)](https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/dsc_3.x/449/)<br /><blockquote><a href=https://github.com/redhat-developer/devspaces-chectl/releases/3.4.0-CI-dsc-assets>3.4.0 CI</a></blockquote>